export interface RFIDPrintLiteral{
    length: number,
    pieceCount: number,
    qty: string,
    boardFoot: string,
    date: Date,
    size_id: number,
    size: string,
    untreatedGrade: string,
    treatedGrade: string,
    requestedGrade_id: number,
    requestedGrade: string,
    grade_id: string,
    receivedGrade: string,
    vendor_id: number,
    vendor: string,
    loadNumber: string,
    user: string,
    po: string,
    data: string | null,
    bunk: number,
    unitCost: number,
    rfidCode_id: number,
    location: string,
    sourceLocation: string
}
export interface RFIDPrintAll{
    length: number,
    pieceCount: number,
    qty: string,
    boardFoot: number,
    date: Date,
    size_id: number,
    size: string,
    untreatedGrade: string,
    treatedGrade: string,
    requestedGrade_id: number,
    requestedGrade: string,
    grade_id: string,
    receivedGrade: string,
    vendor_id: number,
    vendor: string,
    loadNumber: string,
    user: string,
    po: string,
    data: string | null,
    bunk: number,
    unitCost: number,
    rfidCode_id: number,
    location: string,
    sourceLocation: string,
    grade : string,    
}